### ISSUE TITLE
About protoc-gen-dart

### ISSUE THREAD

**Issue by bookshiyi** [cunarist/rinf#123]
Some strange things about version 3.0.0 when built example:

1. The source code passed the CI test on all platforms, but when I tried to compile it on macOS (arm) and Windows, it failed(the folder `lib/messages/` is empty).

2. During the compilation process, when the `protoc-gen-dart` program is not found, the `build.rs` will not terminate or report any error.

3. In the `build.rs` and CI, the environment variable of $HOME/.pub-cache/bin is not set separately, but it has been passed the CI test.

Maybe need to improve:

1. Set environment variable of `protoc-gen-dart`

2. Catch the error of protoc command then terminate task.

I'm not sure if I've overlooked any important steps about protobuf.
How do you think about it?

**Comment by temeddix** [comment]
Good point, I will share my experience with each of those problems:

1. Not sure why, but simply running `cargo check` generated the message code for me. Explicit `cargo check` should not be needed, but that was a workaround. It would be good to find out why though :|
1. I tried to solve this, but it turned out to be a bug with protobuf: https://github.com/protocolbuffers/protobuf/issues/10486
1. Also not sure why, but my assumption was that `protoc` was finding for Dart's `protoc_plugin` path with its own logic, not only looking for PATH environment variable.

Please tell me if there were any misunderstandings :) And parts that you think we should investigate or improve

**Comment by bookshiyi** [comment]
When run command `dart pub global activate protoc_plugin` manually, we could get the log:

```
Package protoc_plugin is currently active at version 21.1.1.
The package protoc_plugin is already activated at newest available version.
To recompile executables, first run `dart pub global deactivate protoc_plugin`.
Installed executable protoc-gen-dart.
Warning: Pub installs executables into $HOME/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

  export PATH="$PATH":"$HOME/.pub-cache/bin"

Activated protoc_plugin 21.1.1.
```

What puzzles me is that in version 3.0.0, the path of protoc-gen-dart is not added to the environment variable PATH, so how is the code under the lib/messages/ folder generated?

**Comment by bookshiyi** [comment]
1. Is the effect of command `cargo check` is only generate files to `lib/messages/` ?

2. I have attempt to use `command.status().unwrap().success()` to check if any compilation error of `protoc`, it seem like work well.

3. Oh, I think your speculation is very convincing. 
Protoc bypassed `PATH` and directly found the location of the `protoc-gen-dart` program.

**Comment by temeddix** [comment]
For question 1, `cargo check` invokes `./native/hub/build.rs`, which generates message files from `.proto` files :) It's originally for checking Rust errors, but it also invokes `build.rs` file.

I do feel like proposing to use `cargo check` only to generate messages is not 100% appropriate though 😅.
