### ISSUE TITLE
Serialize/Deserialize

### ISSUE THREAD

**Issue by sergiomeneses** [cunarist/rinf#127]
First of all, congratz for this lib.

Just have a question/concern about the approach taked on type-safe messages in the recent release, why use protobuf when we can use libs in rust ecosystem like [this one](https://github.com/zakarumych/alkahest)?

Can we extended or add another libs for type-safe messages?, there is a guidance about how to implement other options (like the proposed)?, thanks.

**Comment by temeddix** [comment]
Yeah, you can remove Protobuf and use other serialization method you like :) This is possible because data being passed between Dart and Rust are basically bytes arrays.

`alkahest` seems to be a decent serialization library for Rust, but it doesn't seem to support Dart code gen/serialization. We adopted Protobuf to ensure type-safety from **"same"** messages(`.proto`) in both Dart and Rust. Protobuf was currently the most widely-used language-neutral message generator.
