### ISSUE TITLE
Well known types from protobuf

### ISSUE THREAD

**Issue by LucaCoduriV** [cunarist/rinf#170]
Hello, I am using timestamps in my proto file but `rifs message` seems to not automatically compile that type.
I finally got it working by using this command `protoc --dart_out=./lib/messages google/protobuf/timestamp.proto`.
I maybe missed something but I think it would be nice to say something about that in the documentation.

**Comment by temeddix** [comment]
Thanks for the report :)

I will inspect this soon. Do you mind sharing that proto file's content here with timestamps so that I can solve it faster?

**Comment by LucaCoduriV** [comment]
```proto
syntax = "proto3";
package daemon_event;

import "google/protobuf/timestamp.proto";

message Notification {
  uint32 id = 1;
  string app_name = 2;
  uint32 replaces_id = 3;
  string summary = 4;
  string body = 5;
  repeated string actions = 6;
  int32 timeout = 7;
  google.protobuf.Timestamp created_at = 8;
}
```
Here is the full file:
https://github.com/LucaCoduriV/Notiflut-Land/blob/1591df17f8f0a53ee5e36e2c34daeac0be132d2b/notiflut_daemon/messages/daemon_event.proto

**Comment by temeddix** [comment]
https://github.com/grpc/grpc-dart/blob/master/example/googleapis/lib/src/generated/google/protobuf/timestamp.pb.dart

Looks like Google has various default `.proto` imports. The question lies where Rust files are automatically using those, but you need to specify Google module when running `protoc` for Dart.

https://github.com/cunarist/rust-in-flutter/blob/e010627657455d7760ed22bce3662d9b019f56c9/bin/rust_in_flutter.dart#L467-L475

There should be a way to support those Google imports, but I'm not sure if we should include all google imports in that command code. What's your opinion?

**Comment by LucaCoduriV** [comment]
I don't think they should be imported by default.
But maybe you could add some args for rifs that adds the needed proto files.
Or an easier way is just to tell what to do in case we need it in the documentation.

**Comment by temeddix** [comment]
Yeah, as you said I think describing how to include Google imports in the docs would be enough :)

I still do have one question: If you want to import Google `.proto` files, isn't including them in the `./messages` folder of your Flutter app project enough? We can get them easily since they are distributed with the compiled binary. (I'm not experienced with Google `.proto` imports, so I might be missing something)

https://github.com/protocolbuffers/protobuf/releases
<img width="872" alt="image" src="https://github.com/cunarist/rust-in-flutter/assets/66480156/5d7869ca-1e17-40ad-9cb5-bca57c094035">

If you think that describing how to import Google `.proto` files in the docs would be better, I will be happy to receive your help. If you have any suggestions, please leave a PR or you could share your description text in this thread, if you don't mind.

**Comment by LucaCoduriV** [comment]
Sorry, for late response.
I'll take a look at that today.

**Comment by temeddix** [comment]
Just wanted to mention that documentation files are in `./documentations` folder of this repository :D
