### ISSUE TITLE
Breakpoints in Rust code

### ISSUE THREAD

**Issue by NightBlaze** [cunarist/rinf#223]
Is it possible to debug Rust code with breakpoints?

**Comment by temeddix** [comment]
Hi @NightBlaze 

Unfortunately it is not possible to debug Rust code with breakpoints directly inside Flutter app, because Flutter has the full control of the app.

Instead, I think you can write your own unit tests in Rust to test your code with breakpoints.

- https://stackoverflow.com/questions/50707118/how-to-debug-rust-unit-tests-on-windows

Hope it helps :) If not, please share your opinion more here. Perhaps it could be things about docs or template.

**Comment by erlangparasu** [comment]
how about Hot Reload ?

**Comment by temeddix** [comment]
Hot reload and hot restart should work well, Rinf does consider those. Give it a try :)

**Comment by erlangparasu** [comment]
i mean, auto recompile

**Comment by temeddix** [comment]
Unfortunately, auto-recompilation of Rust is technically not possible.

- https://rinf-docs.cunarist.com/frequently-asked-questions/#will-changes-made-to-rust-code-take-effect-upon-darts-hot-restart

> No, the updated Rust code cannot be loaded upon Dart's hot restart. To incorporate the changes, the app needs to be re-compiled, as the app binary must be linked to the newly compiled Rust library files again. This limitation arises from the Rust compilation process, as Rust does not inherently support a hot restart feature. Still, Dart's hot restart does restart the Rust logic, in other words, the main() function.

**Comment by erlangparasu** [comment]
> Unfortunately, auto-recompilation of Rust is technically not possible.
> 
>     * https://rinf-docs.cunarist.com/frequently-asked-questions/#will-changes-made-to-rust-code-take-effect-upon-darts-hot-restart
> 
> 
> > No, the updated Rust code cannot be loaded upon Dart's hot restart. To incorporate the changes, the app needs to be re-compiled, as the app binary must be linked to the newly compiled Rust library files again. This limitation arises from the Rust compilation process, as Rust does not inherently support a hot restart feature. Still, Dart's hot restart does restart the Rust logic, in other words, the main() function.

@temeddix  Thank you for the information

**Comment by erlangparasu** [comment]
any suggestions for testing rust side?

**Comment by NightBlaze** [comment]
I see. [gomobile](https://pkg.go.dev/golang.org/x/mobile/cmd/gomobile) also doesn't support breakpoints and it was not very convenient to use Oldschool Println Debuging on the project. While unit testing is helpful, there are times when debugging with breakpoints is faster and easier. It seems that debugging in `rinf` debugging is possible only with print.

By the way, idk how but when I tested Rust + Swift then Xcode allows to set breakpoints in Rust code.

**Comment by temeddix** [comment]
I'm also curious about how breakpoints can work in Rust+Swift, maybe we can discuss about it further if it's possible :) We are open to any kind of PR that brings these conveniences.

**Comment by erlangparasu** [comment]
`crate::debug_print` not print any text on console

**Comment by NightBlaze** [comment]
> I'm also curious about how breakpoints can work in Rust+Swift, maybe we can discuss about it further if it's possible :) We are open to any kind of PR that brings these conveniences.

Don't think that I can help with it because of my level  of the knowledge of the thing. It's just works. Also Xcode shows warnings/errors of Rust code. I just followed this tutorial https://blog.mozilla.org/data/2022/01/31/this-week-in-glean-building-and-deploying-a-rust-library-on-ios/

**Comment by temeddix** [comment]
- https://github.com/irondash/cargokit/issues/41

**Comment by temeddix** [comment]
It turns out that breakpoints only work when a Rust executable is directly executed from the IDE(e.g. VSCode) that provides breakpoint information.

For example, if you Run a Flutter app from VSCode's debugging panel, breakpoints do work.
<img width="437" alt="image" src="https://github.com/cunarist/rinf/assets/66480156/dcd21ac0-749b-4c79-aa4e-15c591881e71">

However, if you Run a Flutter app directly in the terminal, even Dart breakpoints don't work.
```bash
flutter run
```

Since Rust library is linked to the Flutter binary by Cargokit, which has nothing to do with IDE's debugging tools, it's no wonder that breakpoints don't work.

There *are* ways to make native Rust breakpoints work, by attaching native debuggers to the Flutter app's process, but this seems to be very tedious and platform-specific.

- https://docs.flutter.dev/testing/native-debugging

Closing as it's not really solvable, please ask more questions here, if any :)
