### ISSUE TITLE
Does this work with rust and add ons?

### ISSUE THREAD

**Issue by jdprojectcentral** [cunarist/rinf#454]
When you use the flutter rust bridge are you able to use rust add ons? For exmaple ThirtyFour crate and others etc?

Also using some of the same steps could I just move my current rust repo into my flutter project and just use the command lines for codegen etc?

**Comment by temeddix** [comment]
Hi :)

Yeah, Rinf definitely supports multiple crates. If you have crates to bring in, just put them all in the `native` folder and make the `hub` crate use them.

If you're using codegen, you might need to adjust some path arguments because FRB and Rinf's paths are a bit different, but it can still work.
