### ISSUE TITLE
android build failed

### ISSUE THREAD

**Issue by moluopro** [cunarist/rinf#61]
The version of rust_in_flutter is 1.1.1 and running the official example packaged for Android gives the following error :    

![image](https://github.com/cunarist/rust-in-flutter/assets/55039286/f602fcf6-1720-4610-9d49-da8368cd828f)  

And also I would like to know where the built dynamic libraries are put by default ?

**Comment by moluopro** [comment]
run `flutter build apk --release` and get the same result

**Comment by temeddix** [comment]
I'll investigate this issue soon and share the progress. Thanks for your report!

**Comment by temeddix** [comment]
@MoLuoPro I confirmed the problem and fixed the issue. Rust-In-Flutter 1.3.1 will not print those errors anymore.

This problem was due to the difference between environment variables produced by Flutter in Windows and macOS. On macOS, the Android path could be detected with the `PWD` environment variable, which was not present on Windows. Now the path detection uses gradle variables instead of environment variables, which are always available.

**Comment by temeddix** [comment]
@MoLuoPro The dynamic library file is already embedded in the `.apk` file. If you change the extension of that `.apk` file into `.zip` and unzip it, you can find a library named `libhub.so`.

All build settings of Rust-In-Flutter ensures that all library files are properly included in the final build, ready to be distributed.

<img width="732" alt="image" src="https://github.com/cunarist/rust-in-flutter/assets/66480156/b8dbfc2f-b545-456f-aeba-61910794f9de">

Thank you for your taking the time to report this issue. Please feel free to come back again if there are any other problems! :)

**Comment by moluopro** [comment]
OK, thanks for your help !
