### ISSUE TITLE
Need a newbie tutorial doc

### ISSUE THREAD

**Issue by moluopro** [cunarist/rinf#66]
Specifically, from creating a new flutter project to running a `rust-in-flutter` project step-by-step: show different types of functions as examples: simple math calculations and returning the result, dart passing an array to Rust, dart passing a string to rust and then returning another string, etc.

**Comment by temeddix** [comment]
This is a good idea :) It would be nice to let users adopt this package more easily. Though it would be better to avoid explaining steps that other tutorials do better, more detailed communication examples and setup procedure can be provided.

By the way, which people do you think that those new guides should target? People with Rust background, or Flutter background, or both, or complete newbies?

**Comment by moluopro** [comment]
I think the tutorial should be geared towards Flutter developers with a little bit of Rust foundation rather than the professional Rust programming crowd. The library should make it easy for Flutter users to convert Rust libraries into packages usable by Flutter.

**Comment by moluopro** [comment]
If you write a new tutorial doc, I'm willing to be the first to provide Chinese translation work. The other thing is, would you consider making a `rust_in_dart` to provide easy usage similar to this library?

**Comment by temeddix** [comment]
Yeah, it would be nice to have `rust_in_dart` addition, but this package hooks onto Flutter SDK's build setups for automating Rust compilation and linking for convenience😉 right now. That's why this package only supports Flutter SDK.  When using Dart SDK, you have to manually compile Rust crates. However, I'm investigating the ways to support pure Dart projects as a new addition.

**Comment by temeddix** [comment]
For tutorials, I believe it would be better to only have one `README.md` file because it appears on [pub.dev](https://pub.dev/packages/rust_in_flutter) and GitHub main page.

I will add some more sections and content in `README.md` as you mentioned. Thank you for your ideas, I will share the progress when there are updates in the guides!

**Comment by moluopro** [comment]
I also think that at the current size of the project, the doc should just be placed in the `Readme.md`

**Comment by moluopro** [comment]
Looking forward to your new docs!

**Comment by temeddix** [comment]
@moluopro The step-by-step tutorial is now added. I generated Chinese translations which might look awkward, so please fix various grammar and sentences when you are free!

**Comment by temeddix** [comment]
I will also be fixing some errors in the guides and add some more about MessagePack types and organize sections in a day or two :)

**Comment by moluopro** [comment]
okk

**Comment by moluopro** [comment]
I also need to make some changes to the English doc, about the doc structure

**Comment by temeddix** [comment]
If you have a better idea about organizing the base guide structure, feel free to leave a PR so that we can discuss about this!

**Comment by moluopro** [comment]
Just changed the tips to FAQ and moved the question about ndkVersion to here. 

I don't think users have to consult about Android packaging failures before they start using our library, so moved this section to the FAQ.

**Comment by moluopro** [comment]
My pr is coming ~ QAQ

**Comment by temeddix** [comment]
That change looks reasonable, looking forward to read your PR!
